- hosts: jenkins
  vars:
    jenkins_hostname: localhost
  roles:
    - role: java
      become: yes
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    
    - role: java
      become: yes
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk 
    - role: jenkins
      become: yes
